'''
Interface Grafica do Pasolv Versao Master
'''


from extensoes.Dependencies import *
from GetEnvPath import *


class Ui_PasolvMainWindow(object):
    def setupUi(self, PasolvMainWindow):
        PasolvMainWindow.setObjectName("PasolvMainWindow")
        PasolvMainWindow.resize(819, 578)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PasolvMainWindow.sizePolicy().hasHeightForWidth())
        PasolvMainWindow.setSizePolicy(sizePolicy)
        PasolvMainWindow.setMouseTracking(False)
        PasolvMainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon.fromTheme(GPC.Recursos+"Icon.png")
        PasolvMainWindow.setWindowIcon(icon)
        PasolvMainWindow.setAutoFillBackground(False)
        PasolvMainWindow.setStyleSheet("background-color: rgb(17, 26, 25);")
        self.centralwidget = QtWidgets.QWidget(PasolvMainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(819, 537))
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.PasolvTabs = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PasolvTabs.sizePolicy().hasHeightForWidth())
        self.PasolvTabs.setSizePolicy(sizePolicy)
        self.PasolvTabs.setMinimumSize(QtCore.QSize(741, 531))
        self.PasolvTabs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PasolvTabs.setAutoFillBackground(False)
        self.PasolvTabs.setStyleSheet("background-color: rgb(81, 81, 81);")
        self.PasolvTabs.setObjectName("PasolvTabs")
        self.P_tab2 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.P_tab2.sizePolicy().hasHeightForWidth())
        self.P_tab2.setSizePolicy(sizePolicy)
        self.P_tab2.setStyleSheet("background: url(:/background.jpg)")
        self.P_tab2.setObjectName("P_tab2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.P_tab2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.VariavelLabel = QtWidgets.QLabel(self.P_tab2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.VariavelLabel.setFont(font)
        self.VariavelLabel.setAutoFillBackground(False)
        self.VariavelLabel.setObjectName("VariavelLabel")
        self.gridLayout_3.addWidget(self.VariavelLabel, 5, 0, 1, 1)
        self.AddFormula = QtWidgets.QPushButton(self.P_tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddFormula.sizePolicy().hasHeightForWidth())
        self.AddFormula.setSizePolicy(sizePolicy)
        self.AddFormula.setStyleSheet("background-color: rgb(175, 175, 175);")
        self.AddFormula.setObjectName("AddFormula")
        self.gridLayout_3.addWidget(self.AddFormula, 4, 0, 1, 1)
        self.FormulaGraphic = QtWidgets.QGraphicsView(self.P_tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FormulaGraphic.sizePolicy().hasHeightForWidth())
        self.FormulaGraphic.setSizePolicy(sizePolicy)
        self.FormulaGraphic.setStyleSheet("background-color: rgb(175, 175, 175);")
        self.FormulaGraphic.setTransformationAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.FormulaGraphic.setObjectName("FormulaGraphic")
        self.gridLayout_3.addWidget(self.FormulaGraphic, 0, 12, 15, 1)
        self.FormulaList = QtWidgets.QListWidget(self.P_tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FormulaList.sizePolicy().hasHeightForWidth())
        self.FormulaList.setSizePolicy(sizePolicy)
        self.FormulaList.setStyleSheet("background-color: rgb(175, 175, 175);")
        self.FormulaList.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.SelectedClicked)
        self.FormulaList.setResizeMode(QtWidgets.QListView.Adjust)
        self.FormulaList.setItemAlignment(QtCore.Qt.AlignLeading)
        self.FormulaList.setObjectName("FormulaList")
        self.gridLayout_3.addWidget(self.FormulaList, 14, 0, 1, 2)
        self.FormulaResult = QtWidgets.QLabel(self.P_tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FormulaResult.sizePolicy().hasHeightForWidth())
        self.FormulaResult.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.FormulaResult.setFont(font)
        self.FormulaResult.setObjectName("FormulaResult")
        self.gridLayout_3.addWidget(self.FormulaResult, 9, 0, 1, 1)
        self.ResultOutPut = QtWidgets.QLineEdit(self.P_tab2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ResultOutPut.setFont(font)
        self.ResultOutPut.setTabletTracking(False)
        self.ResultOutPut.setStyleSheet("background-color: rgb(175, 175, 175);")
        self.ResultOutPut.setText("")
        self.ResultOutPut.setObjectName("ResultOutPut")
        self.gridLayout_3.addWidget(self.ResultOutPut, 10, 0, 1, 1)
        self.FormulaLabel = QtWidgets.QLabel(self.P_tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FormulaLabel.sizePolicy().hasHeightForWidth())
        self.FormulaLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.FormulaLabel.setFont(font)
        self.FormulaLabel.setObjectName("FormulaLabel")
        self.gridLayout_3.addWidget(self.FormulaLabel, 2, 0, 1, 1)
        self.FormulaInput = FormulaInputClass(self.P_tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FormulaInput.sizePolicy().hasHeightForWidth())
        self.FormulaInput.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold")
        self.FormulaInput.setFont(font)
        self.FormulaInput.setAutoFillBackground(False)
        self.FormulaInput.setStyleSheet("background-color: rgb(175, 175, 175);")
        self.FormulaInput.setText("")
        self.FormulaInput.setDragEnabled(True)
        self.FormulaInput.setClearButtonEnabled(False)
        self.FormulaInput.setObjectName("FormulaInput")
        self.gridLayout_3.addWidget(self.FormulaInput, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 11, 0, 1, 1)
        self.AddVariavel = QtWidgets.QPushButton(self.P_tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddVariavel.sizePolicy().hasHeightForWidth())
        self.AddVariavel.setSizePolicy(sizePolicy)
        self.AddVariavel.setStyleSheet("background-color: rgb(175, 175, 175);")
        self.AddVariavel.setObjectName("AddVariavel")
        self.gridLayout_3.addWidget(self.AddVariavel, 8, 0, 1, 1)
        self.VariavelInput = FormulaInputClass(self.P_tab2)
        self.VariavelInput.setStyleSheet("background-color: rgb(175, 175, 175);")
        self.VariavelInput.setObjectName("VariavelInput")
        self.gridLayout_3.addWidget(self.VariavelInput, 7, 0, 1, 1)
        self.RemoveItem = QtWidgets.QPushButton(self.P_tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RemoveItem.sizePolicy().hasHeightForWidth())
        self.RemoveItem.setSizePolicy(sizePolicy)
        self.RemoveItem.setStyleSheet("background-color: rgb(255, 20, 20);")
        self.RemoveItem.setObjectName("RemoveItem")
        self.gridLayout_3.addWidget(self.RemoveItem, 12, 0, 1, 1)
        icon = QtGui.QIcon.fromTheme(GPC.Recursos+"formulaicon.png")
        self.PasolvTabs.addTab(self.P_tab2, icon, "")
        self.P_tab1 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.P_tab1.sizePolicy().hasHeightForWidth())
        self.P_tab1.setSizePolicy(sizePolicy)
        self.P_tab1.setObjectName("P_tab1")
        self.gridLayout = QtWidgets.QGridLayout(self.P_tab1)
        self.gridLayout.setObjectName("gridLayout")
        self.Geometric_GL = QtWidgets.QOpenGLWidget(self.P_tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Geometric_GL.sizePolicy().hasHeightForWidth())
        self.Geometric_GL.setSizePolicy(sizePolicy)
        self.Geometric_GL.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.Geometric_GL.setMouseTracking(True)
        self.Geometric_GL.setObjectName("Geometric_GL")
        self.gridLayout.addWidget(self.Geometric_GL, 1, 0, 1, 1)
        self.G_Formula_Label = QtWidgets.QLabel(self.P_tab1)
        font = QtGui.QFont()
        font.setFamily("Impact")
        self.G_Formula_Label.setFont(font)
        self.G_Formula_Label.setAutoFillBackground(False)
        self.G_Formula_Label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.G_Formula_Label.setLineWidth(1)
        self.G_Formula_Label.setTextFormat(QtCore.Qt.RichText)
        self.G_Formula_Label.setScaledContents(False)
        self.G_Formula_Label.setObjectName("G_Formula_Label")
        self.gridLayout.addWidget(self.G_Formula_Label, 0, 1, 1, 1)
        self.Geometric_GL_Label = QtWidgets.QLabel(self.P_tab1)
        font = QtGui.QFont()
        font.setFamily("Impact")
        self.Geometric_GL_Label.setFont(font)
        self.Geometric_GL_Label.setAutoFillBackground(False)
        self.Geometric_GL_Label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Geometric_GL_Label.setLineWidth(1)
        self.Geometric_GL_Label.setTextFormat(QtCore.Qt.RichText)
        self.Geometric_GL_Label.setScaledContents(False)
        self.Geometric_GL_Label.setObjectName("Geometric_GL_Label")
        self.gridLayout.addWidget(self.Geometric_GL_Label, 0, 0, 1, 1)
        self.FormulaList_2 = QtWidgets.QListWidget(self.P_tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FormulaList_2.sizePolicy().hasHeightForWidth())
        self.FormulaList_2.setSizePolicy(sizePolicy)
        self.FormulaList_2.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.FormulaList_2.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.SelectedClicked)
        self.FormulaList_2.setSelectionRectVisible(True)
        self.FormulaList_2.setObjectName("FormulaList_2")
        self.gridLayout.addWidget(self.FormulaList_2, 1, 1, 1, 1)
        icon = QtGui.QIcon.fromTheme(GPC.Recursos+"geometricicon.png")
        self.PasolvTabs.addTab(self.P_tab1, icon, "")
        self.gridLayout_4.addWidget(self.PasolvTabs, 0, 0, 1, 1)
        PasolvMainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(PasolvMainWindow)
        self.statusbar.setObjectName("statusbar")
        PasolvMainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(PasolvMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 819, 19))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.menubar.setFont(font)
        self.menubar.setStyleSheet("background-color: rgb(59, 59, 59);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"text-color: rgb(255, 255, 255);")
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.FileNew = QtWidgets.QMenu(self.menuFile)
        self.FileNew.setAutoFillBackground(False)
        self.FileNew.setObjectName("FileNew")
        self.menuImport = QtWidgets.QMenu(self.menubar)
        self.menuImport.setObjectName("menuImport")
        self.menuexport = QtWidgets.QMenu(self.menubar)
        self.menuexport.setObjectName("menuexport")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        PasolvMainWindow.setMenuBar(self.menubar)
        self.ImportConfig = QtWidgets.QAction(PasolvMainWindow)
        self.ImportConfig.setObjectName("ImportConfig")
        self.ImportGeometry = QtWidgets.QAction(PasolvMainWindow)
        self.ImportGeometry.setObjectName("ImportGeometry")
        self.ImportFormula = QtWidgets.QAction(PasolvMainWindow)
        self.ImportFormula.setObjectName("ImportFormula")
        self.FileOpen = QtWidgets.QAction(PasolvMainWindow)
        self.FileOpen.setObjectName("FileOpen")
        self.FileSave = QtWidgets.QAction(PasolvMainWindow)
        self.FileSave.setObjectName("FileSave")
        self.NewGeometry = QtWidgets.QAction(PasolvMainWindow)
        self.NewGeometry.setObjectName("NewGeometry")
        self.actionFormula_2 = QtWidgets.QAction(PasolvMainWindow)
        self.actionFormula_2.setObjectName("actionFormula_2")
        self.ExportFormula = QtWidgets.QAction(PasolvMainWindow)
        self.ExportFormula.setObjectName("ExportFormula")
        self.ExportGeometry = QtWidgets.QAction(PasolvMainWindow)
        self.ExportGeometry.setObjectName("ExportGeometry")
        self.ExportConfig = QtWidgets.QAction(PasolvMainWindow)
        self.ExportConfig.setObjectName("ExportConfig")
        self.AboutCreator = QtWidgets.QAction(PasolvMainWindow)
        self.AboutCreator.setObjectName("AboutCreator")
        self.AboutPDC_Pasolv_Master = QtWidgets.QAction(PasolvMainWindow)
        self.AboutPDC_Pasolv_Master.setObjectName("AboutPDC_Pasolv_Master")
        self.FileNew.addAction(self.NewGeometry)
        self.menuFile.addAction(self.FileNew.menuAction())
        self.menuFile.addAction(self.FileOpen)
        self.menuFile.addAction(self.FileSave)
        self.menuImport.addAction(self.ImportConfig)
        self.menuImport.addAction(self.ImportGeometry)
        self.menuImport.addAction(self.ImportFormula)
        self.menuexport.addAction(self.ExportFormula)
        self.menuexport.addAction(self.ExportGeometry)
        self.menuexport.addAction(self.ExportConfig)
        self.menuAbout.addAction(self.AboutCreator)
        self.menuAbout.addAction(self.AboutPDC_Pasolv_Master)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuImport.menuAction())
        self.menubar.addAction(self.menuexport.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(PasolvMainWindow)
        self.PasolvTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PasolvMainWindow)

    def retranslateUi(self, PasolvMainWindow):
        _translate = QtCore.QCoreApplication.translate
        PasolvMainWindow.setWindowTitle(_translate("PasolvMainWindow", "PDC Pasolv Master v0.87.5"))
        self.VariavelLabel.setText(_translate("PasolvMainWindow", "Varivel:"))
        self.AddFormula.setText(_translate("PasolvMainWindow", "Add"))
        self.FormulaResult.setText(_translate("PasolvMainWindow", "Result:"))
        self.ResultOutPut.setPlaceholderText(_translate("PasolvMainWindow", "Resultado"))
        self.FormulaLabel.setText(_translate("PasolvMainWindow", "Formula:"))
        self.FormulaInput.setPlaceholderText(_translate("PasolvMainWindow", "F(x,y) = ax^n + by^k"))
        self.AddVariavel.setText(_translate("PasolvMainWindow", "Add"))
        self.VariavelInput.setPlaceholderText(_translate("PasolvMainWindow", "X = 123.123"))
        self.RemoveItem.setText(_translate("PasolvMainWindow", "Remover Item Selecionado"))
        self.PasolvTabs.setTabText(self.PasolvTabs.indexOf(self.P_tab2), _translate("PasolvMainWindow", "Formula"))
        self.G_Formula_Label.setText(_translate("PasolvMainWindow", "Formula List"))
        self.Geometric_GL_Label.setText(_translate("PasolvMainWindow", "3D Geometric"))
        self.PasolvTabs.setTabText(self.PasolvTabs.indexOf(self.P_tab1), _translate("PasolvMainWindow", "Geometric"))
        self.menuFile.setTitle(_translate("PasolvMainWindow", "File"))
        self.FileNew.setTitle(_translate("PasolvMainWindow", "new"))
        self.menuImport.setTitle(_translate("PasolvMainWindow", "Import"))
        self.menuexport.setTitle(_translate("PasolvMainWindow", "Export"))
        self.menuAbout.setTitle(_translate("PasolvMainWindow", "About"))
        self.ImportConfig.setText(_translate("PasolvMainWindow", "Config"))
        self.ImportGeometry.setText(_translate("PasolvMainWindow", "Geometry"))
        self.ImportFormula.setText(_translate("PasolvMainWindow", "Formula"))
        self.FileOpen.setText(_translate("PasolvMainWindow", "open"))
        self.FileSave.setText(_translate("PasolvMainWindow", "save"))
        self.NewGeometry.setText(_translate("PasolvMainWindow", "Geometry"))
        self.actionFormula_2.setText(_translate("PasolvMainWindow", "Formula"))
        self.ExportFormula.setText(_translate("PasolvMainWindow", "Formula"))
        self.ExportGeometry.setText(_translate("PasolvMainWindow", "Geometry"))
        self.ExportConfig.setText(_translate("PasolvMainWindow", "Config"))
        self.AboutCreator.setText(_translate("PasolvMainWindow", "Creator"))
        self.AboutPDC_Pasolv_Master.setText(_translate("PasolvMainWindow", "PDC Pasolv Master"))
from formulainputclass import FormulaInputClass
