# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\GUILHERME\Desktop\PDC PASOLV Master\ITMG\PDC Pasolv Master.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PasolvMainWindow(object):
    def setupUi(self, PasolvMainWindow):
        PasolvMainWindow.setObjectName("PasolvMainWindow")
        PasolvMainWindow.resize(819, 578)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PasolvMainWindow.sizePolicy().hasHeightForWidth())
        PasolvMainWindow.setSizePolicy(sizePolicy)
        PasolvMainWindow.setMouseTracking(False)
        PasolvMainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon.fromTheme("PasolvIcon.png")
        PasolvMainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(PasolvMainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(819, 537))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.PasolvTabs = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PasolvTabs.sizePolicy().hasHeightForWidth())
        self.PasolvTabs.setSizePolicy(sizePolicy)
        self.PasolvTabs.setMinimumSize(QtCore.QSize(741, 531))
        self.PasolvTabs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PasolvTabs.setAutoFillBackground(False)
        self.PasolvTabs.setObjectName("PasolvTabs")
        self.P_tab2 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.P_tab2.sizePolicy().hasHeightForWidth())
        self.P_tab2.setSizePolicy(sizePolicy)
        self.P_tab2.setObjectName("P_tab2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.P_tab2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.FormulaLabel = QtWidgets.QLabel(self.P_tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FormulaLabel.sizePolicy().hasHeightForWidth())
        self.FormulaLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.FormulaLabel.setFont(font)
        self.FormulaLabel.setObjectName("FormulaLabel")
        self.gridLayout_3.addWidget(self.FormulaLabel, 2, 0, 1, 1)
        self.FormulaInput = QtWidgets.QLineEdit(self.P_tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FormulaInput.sizePolicy().hasHeightForWidth())
        self.FormulaInput.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold")
        self.FormulaInput.setFont(font)
        self.FormulaInput.setAutoFillBackground(True)
        self.FormulaInput.setDragEnabled(True)
        self.FormulaInput.setClearButtonEnabled(False)
        self.FormulaInput.setObjectName("FormulaInput")
        self.gridLayout_3.addWidget(self.FormulaInput, 3, 0, 1, 1)
        self.AddFormula = QtWidgets.QPushButton(self.P_tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddFormula.sizePolicy().hasHeightForWidth())
        self.AddFormula.setSizePolicy(sizePolicy)
        self.AddFormula.setObjectName("AddFormula")
        self.gridLayout_3.addWidget(self.AddFormula, 4, 0, 1, 1)
        self.FormulaList = QtWidgets.QListWidget(self.P_tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FormulaList.sizePolicy().hasHeightForWidth())
        self.FormulaList.setSizePolicy(sizePolicy)
        self.FormulaList.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.SelectedClicked)
        self.FormulaList.setResizeMode(QtWidgets.QListView.Adjust)
        self.FormulaList.setItemAlignment(QtCore.Qt.AlignLeading)
        self.FormulaList.setObjectName("FormulaList")
        self.gridLayout_3.addWidget(self.FormulaList, 6, 0, 1, 1)
        self.FormulaResult = QtWidgets.QLabel(self.P_tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FormulaResult.sizePolicy().hasHeightForWidth())
        self.FormulaResult.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.FormulaResult.setFont(font)
        self.FormulaResult.setObjectName("FormulaResult")
        self.gridLayout_3.addWidget(self.FormulaResult, 5, 0, 1, 2)
        self.FormulaGraphic = QtWidgets.QGraphicsView(self.P_tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FormulaGraphic.sizePolicy().hasHeightForWidth())
        self.FormulaGraphic.setSizePolicy(sizePolicy)
        self.FormulaGraphic.setTransformationAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.FormulaGraphic.setObjectName("FormulaGraphic")
        self.gridLayout_3.addWidget(self.FormulaGraphic, 0, 6, 7, 1)
        icon = QtGui.QIcon.fromTheme("Formulaicon.png")
        self.PasolvTabs.addTab(self.P_tab2, icon, "")
        self.P_tab1 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.P_tab1.sizePolicy().hasHeightForWidth())
        self.P_tab1.setSizePolicy(sizePolicy)
        self.P_tab1.setObjectName("P_tab1")
        self.gridLayout = QtWidgets.QGridLayout(self.P_tab1)
        self.gridLayout.setObjectName("gridLayout")
        self.FormulaList_2 = QtWidgets.QListView(self.P_tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FormulaList_2.sizePolicy().hasHeightForWidth())
        self.FormulaList_2.setSizePolicy(sizePolicy)
        self.FormulaList_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.FormulaList_2.setMouseTracking(False)
        self.FormulaList_2.setObjectName("FormulaList_2")
        self.gridLayout.addWidget(self.FormulaList_2, 1, 1, 1, 1)
        self.Geometric_GL = QtWidgets.QOpenGLWidget(self.P_tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Geometric_GL.sizePolicy().hasHeightForWidth())
        self.Geometric_GL.setSizePolicy(sizePolicy)
        self.Geometric_GL.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.Geometric_GL.setMouseTracking(True)
        self.Geometric_GL.setObjectName("Geometric_GL")
        self.gridLayout.addWidget(self.Geometric_GL, 1, 0, 1, 1)
        self.G_Formula_Label = QtWidgets.QLabel(self.P_tab1)
        font = QtGui.QFont()
        font.setFamily("Impact")
        self.G_Formula_Label.setFont(font)
        self.G_Formula_Label.setAutoFillBackground(False)
        self.G_Formula_Label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.G_Formula_Label.setLineWidth(1)
        self.G_Formula_Label.setTextFormat(QtCore.Qt.RichText)
        self.G_Formula_Label.setScaledContents(False)
        self.G_Formula_Label.setObjectName("G_Formula_Label")
        self.gridLayout.addWidget(self.G_Formula_Label, 0, 1, 1, 1)
        self.Geometric_GL_Label = QtWidgets.QLabel(self.P_tab1)
        font = QtGui.QFont()
        font.setFamily("Impact")
        self.Geometric_GL_Label.setFont(font)
        self.Geometric_GL_Label.setAutoFillBackground(False)
        self.Geometric_GL_Label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Geometric_GL_Label.setLineWidth(1)
        self.Geometric_GL_Label.setTextFormat(QtCore.Qt.RichText)
        self.Geometric_GL_Label.setScaledContents(False)
        self.Geometric_GL_Label.setObjectName("Geometric_GL_Label")
        self.gridLayout.addWidget(self.Geometric_GL_Label, 0, 0, 1, 1)
        icon = QtGui.QIcon.fromTheme("TabsIcon")
        self.PasolvTabs.addTab(self.P_tab1, icon, "")
        self.gridLayout_4.addWidget(self.PasolvTabs, 0, 0, 1, 1)
        PasolvMainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(PasolvMainWindow)
        self.statusbar.setObjectName("statusbar")
        PasolvMainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(PasolvMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 819, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.FileNew = QtWidgets.QMenu(self.menuFile)
        self.FileNew.setObjectName("FileNew")
        self.menuImport = QtWidgets.QMenu(self.menubar)
        self.menuImport.setObjectName("menuImport")
        self.menuexport = QtWidgets.QMenu(self.menubar)
        self.menuexport.setObjectName("menuexport")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        PasolvMainWindow.setMenuBar(self.menubar)
        self.ImportConfig = QtWidgets.QAction(PasolvMainWindow)
        self.ImportConfig.setObjectName("ImportConfig")
        self.ImportGeometry = QtWidgets.QAction(PasolvMainWindow)
        self.ImportGeometry.setObjectName("ImportGeometry")
        self.ImportFormula = QtWidgets.QAction(PasolvMainWindow)
        self.ImportFormula.setObjectName("ImportFormula")
        self.FileOpen = QtWidgets.QAction(PasolvMainWindow)
        self.FileOpen.setObjectName("FileOpen")
        self.FileSave = QtWidgets.QAction(PasolvMainWindow)
        self.FileSave.setObjectName("FileSave")
        self.NewGeometry = QtWidgets.QAction(PasolvMainWindow)
        self.NewGeometry.setObjectName("NewGeometry")
        self.actionFormula_2 = QtWidgets.QAction(PasolvMainWindow)
        self.actionFormula_2.setObjectName("actionFormula_2")
        self.ExportFormula = QtWidgets.QAction(PasolvMainWindow)
        self.ExportFormula.setObjectName("ExportFormula")
        self.ExportGeometry = QtWidgets.QAction(PasolvMainWindow)
        self.ExportGeometry.setObjectName("ExportGeometry")
        self.ExportConfig = QtWidgets.QAction(PasolvMainWindow)
        self.ExportConfig.setObjectName("ExportConfig")
        self.AboutCreator = QtWidgets.QAction(PasolvMainWindow)
        self.AboutCreator.setObjectName("AboutCreator")
        self.AboutPDC_Pasolv_Master = QtWidgets.QAction(PasolvMainWindow)
        self.AboutPDC_Pasolv_Master.setObjectName("AboutPDC_Pasolv_Master")
        self.FileNew.addAction(self.NewGeometry)
        self.menuFile.addAction(self.FileNew.menuAction())
        self.menuFile.addAction(self.FileOpen)
        self.menuFile.addAction(self.FileSave)
        self.menuImport.addAction(self.ImportConfig)
        self.menuImport.addAction(self.ImportGeometry)
        self.menuImport.addAction(self.ImportFormula)
        self.menuexport.addAction(self.ExportFormula)
        self.menuexport.addAction(self.ExportGeometry)
        self.menuexport.addAction(self.ExportConfig)
        self.menuAbout.addAction(self.AboutCreator)
        self.menuAbout.addAction(self.AboutPDC_Pasolv_Master)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuImport.menuAction())
        self.menubar.addAction(self.menuexport.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(PasolvMainWindow)
        self.PasolvTabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(PasolvMainWindow)

    def retranslateUi(self, PasolvMainWindow):
        _translate = QtCore.QCoreApplication.translate
        PasolvMainWindow.setWindowTitle(_translate("PasolvMainWindow", "PDC Pasolv Master v0.85.9"))
        self.FormulaLabel.setText(_translate("PasolvMainWindow", "Formula:"))
        self.FormulaInput.setText(_translate("PasolvMainWindow", "F(x,y) = ax^n + by^k"))
        self.AddFormula.setText(_translate("PasolvMainWindow", "Add"))
        self.FormulaResult.setText(_translate("PasolvMainWindow", "Result:"))
        self.PasolvTabs.setTabText(self.PasolvTabs.indexOf(self.P_tab2), _translate("PasolvMainWindow", "Formula"))
        self.G_Formula_Label.setText(_translate("PasolvMainWindow", "Formula List"))
        self.Geometric_GL_Label.setText(_translate("PasolvMainWindow", "3D Geometric"))
        self.PasolvTabs.setTabText(self.PasolvTabs.indexOf(self.P_tab1), _translate("PasolvMainWindow", "Geometric"))
        self.menuFile.setTitle(_translate("PasolvMainWindow", "File"))
        self.FileNew.setTitle(_translate("PasolvMainWindow", "new"))
        self.menuImport.setTitle(_translate("PasolvMainWindow", "Import"))
        self.menuexport.setTitle(_translate("PasolvMainWindow", "Export"))
        self.menuAbout.setTitle(_translate("PasolvMainWindow", "About"))
        self.ImportConfig.setText(_translate("PasolvMainWindow", "Config"))
        self.ImportGeometry.setText(_translate("PasolvMainWindow", "Geometry"))
        self.ImportFormula.setText(_translate("PasolvMainWindow", "Formula"))
        self.FileOpen.setText(_translate("PasolvMainWindow", "open"))
        self.FileSave.setText(_translate("PasolvMainWindow", "save"))
        self.NewGeometry.setText(_translate("PasolvMainWindow", "Geometry"))
        self.actionFormula_2.setText(_translate("PasolvMainWindow", "Formula"))
        self.ExportFormula.setText(_translate("PasolvMainWindow", "Formula"))
        self.ExportGeometry.setText(_translate("PasolvMainWindow", "Geometry"))
        self.ExportConfig.setText(_translate("PasolvMainWindow", "Config"))
        self.AboutCreator.setText(_translate("PasolvMainWindow", "Creator"))
        self.AboutPDC_Pasolv_Master.setText(_translate("PasolvMainWindow", "PDC Pasolv Master"))
