# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\G-SON\Desktop\PDC Pasolv Master\Pasolv QT Interface\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PasolvMainWindow(object):
    def setupUi(self, PasolvMainWindow):
        PasolvMainWindow.setObjectName("PasolvMainWindow")
        PasolvMainWindow.resize(762, 578)
        PasolvMainWindow.setMouseTracking(False)
        PasolvMainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon.fromTheme("PasolvIcon.png")
        PasolvMainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(PasolvMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.PasolvTabs = QtWidgets.QTabWidget(self.centralwidget)
        self.PasolvTabs.setGeometry(QtCore.QRect(0, 0, 741, 531))
        self.PasolvTabs.setAutoFillBackground(False)
        self.PasolvTabs.setObjectName("PasolvTabs")
        self.P_tab1 = QtWidgets.QWidget()
        self.P_tab1.setObjectName("P_tab1")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.P_tab1)
        self.openGLWidget.setGeometry(QtCore.QRect(400, 30, 311, 221))
        self.openGLWidget.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.openGLWidget.setMouseTracking(True)
        self.openGLWidget.setObjectName("openGLWidget")
        self.listView = QtWidgets.QListView(self.P_tab1)
        self.listView.setGeometry(QtCore.QRect(400, 280, 311, 192))
        self.listView.setObjectName("listView")
        self.GL_Label = QtWidgets.QLabel(self.P_tab1)
        self.GL_Label.setGeometry(QtCore.QRect(420, 10, 61, 15))
        font = QtGui.QFont()
        font.setFamily("Impact")
        self.GL_Label.setFont(font)
        self.GL_Label.setAutoFillBackground(False)
        self.GL_Label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.GL_Label.setLineWidth(1)
        self.GL_Label.setTextFormat(QtCore.Qt.RichText)
        self.GL_Label.setScaledContents(False)
        self.GL_Label.setObjectName("GL_Label")
        self.GL_Label_2 = QtWidgets.QLabel(self.P_tab1)
        self.GL_Label_2.setGeometry(QtCore.QRect(440, 260, 61, 15))
        font = QtGui.QFont()
        font.setFamily("Impact")
        self.GL_Label_2.setFont(font)
        self.GL_Label_2.setAutoFillBackground(False)
        self.GL_Label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.GL_Label_2.setLineWidth(1)
        self.GL_Label_2.setTextFormat(QtCore.Qt.RichText)
        self.GL_Label_2.setScaledContents(False)
        self.GL_Label_2.setObjectName("GL_Label_2")
        self.PasolvTabs.addTab(self.P_tab1, "")
        self.P_tab2 = QtWidgets.QWidget()
        self.P_tab2.setObjectName("P_tab2")
        self.graphicsView = QtWidgets.QGraphicsView(self.P_tab2)
        self.graphicsView.setGeometry(QtCore.QRect(355, 10, 361, 331))
        self.graphicsView.setObjectName("graphicsView")
        self.lineEdit = QtWidgets.QLineEdit(self.P_tab2)
        self.lineEdit.setGeometry(QtCore.QRect(10, 50, 291, 21))
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold")
        self.lineEdit.setFont(font)
        self.lineEdit.setAutoFillBackground(True)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.P_tab2)
        self.pushButton.setGeometry(QtCore.QRect(230, 80, 71, 23))
        self.pushButton.setObjectName("pushButton")
        self.listView_2 = QtWidgets.QListView(self.P_tab2)
        self.listView_2.setGeometry(QtCore.QRect(10, 120, 321, 221))
        self.listView_2.setObjectName("listView_2")
        self.PasolvTabs.addTab(self.P_tab2, "")
        PasolvMainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(PasolvMainWindow)
        self.statusbar.setObjectName("statusbar")
        PasolvMainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(PasolvMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 762, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menunew = QtWidgets.QMenu(self.menuFile)
        self.menunew.setObjectName("menunew")
        self.menuImport = QtWidgets.QMenu(self.menubar)
        self.menuImport.setObjectName("menuImport")
        self.menuexport = QtWidgets.QMenu(self.menubar)
        self.menuexport.setObjectName("menuexport")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        PasolvMainWindow.setMenuBar(self.menubar)
        self.actionConfig = QtWidgets.QAction(PasolvMainWindow)
        self.actionConfig.setObjectName("actionConfig")
        self.actionGeometry = QtWidgets.QAction(PasolvMainWindow)
        self.actionGeometry.setObjectName("actionGeometry")
        self.actionFormula = QtWidgets.QAction(PasolvMainWindow)
        self.actionFormula.setObjectName("actionFormula")
        self.actionopen = QtWidgets.QAction(PasolvMainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionsave = QtWidgets.QAction(PasolvMainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionGeometry_2 = QtWidgets.QAction(PasolvMainWindow)
        self.actionGeometry_2.setObjectName("actionGeometry_2")
        self.actionFormula_2 = QtWidgets.QAction(PasolvMainWindow)
        self.actionFormula_2.setObjectName("actionFormula_2")
        self.actionFormula_3 = QtWidgets.QAction(PasolvMainWindow)
        self.actionFormula_3.setObjectName("actionFormula_3")
        self.actionGeometry_3 = QtWidgets.QAction(PasolvMainWindow)
        self.actionGeometry_3.setObjectName("actionGeometry_3")
        self.actionConfig_2 = QtWidgets.QAction(PasolvMainWindow)
        self.actionConfig_2.setObjectName("actionConfig_2")
        self.actionCreator = QtWidgets.QAction(PasolvMainWindow)
        self.actionCreator.setObjectName("actionCreator")
        self.actionPDC_Pasolv_Master = QtWidgets.QAction(PasolvMainWindow)
        self.actionPDC_Pasolv_Master.setObjectName("actionPDC_Pasolv_Master")
        self.menunew.addAction(self.actionGeometry_2)
        self.menuFile.addAction(self.menunew.menuAction())
        self.menuFile.addAction(self.actionopen)
        self.menuFile.addAction(self.actionsave)
        self.menuImport.addAction(self.actionConfig)
        self.menuImport.addAction(self.actionGeometry)
        self.menuImport.addAction(self.actionFormula)
        self.menuexport.addAction(self.actionFormula_3)
        self.menuexport.addAction(self.actionGeometry_3)
        self.menuexport.addAction(self.actionConfig_2)
        self.menuAbout.addAction(self.actionCreator)
        self.menuAbout.addAction(self.actionPDC_Pasolv_Master)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuImport.menuAction())
        self.menubar.addAction(self.menuexport.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(PasolvMainWindow)
        self.PasolvTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PasolvMainWindow)

    def retranslateUi(self, PasolvMainWindow):
        _translate = QtCore.QCoreApplication.translate
        PasolvMainWindow.setWindowTitle(_translate("PasolvMainWindow", "PDC Pasolv Master v0.85.9"))
        self.GL_Label.setText(_translate("PasolvMainWindow", "3D Geometric"))
        self.GL_Label_2.setText(_translate("PasolvMainWindow", "Formula List"))
        self.PasolvTabs.setTabText(self.PasolvTabs.indexOf(self.P_tab1), _translate("PasolvMainWindow", "Geometric"))
        self.lineEdit.setText(_translate("PasolvMainWindow", "F(x,y) = ax^n + by^k"))
        self.pushButton.setText(_translate("PasolvMainWindow", "Add"))
        self.PasolvTabs.setTabText(self.PasolvTabs.indexOf(self.P_tab2), _translate("PasolvMainWindow", "Formula"))
        self.menuFile.setTitle(_translate("PasolvMainWindow", "File"))
        self.menunew.setTitle(_translate("PasolvMainWindow", "new"))
        self.menuImport.setTitle(_translate("PasolvMainWindow", "Import"))
        self.menuexport.setTitle(_translate("PasolvMainWindow", "Export"))
        self.menuAbout.setTitle(_translate("PasolvMainWindow", "About"))
        self.actionConfig.setText(_translate("PasolvMainWindow", "Config"))
        self.actionGeometry.setText(_translate("PasolvMainWindow", "Geometry"))
        self.actionFormula.setText(_translate("PasolvMainWindow", "Formula"))
        self.actionopen.setText(_translate("PasolvMainWindow", "open"))
        self.actionsave.setText(_translate("PasolvMainWindow", "save"))
        self.actionGeometry_2.setText(_translate("PasolvMainWindow", "Geometry"))
        self.actionFormula_2.setText(_translate("PasolvMainWindow", "Formula"))
        self.actionFormula_3.setText(_translate("PasolvMainWindow", "Formula"))
        self.actionGeometry_3.setText(_translate("PasolvMainWindow", "Geometry"))
        self.actionConfig_2.setText(_translate("PasolvMainWindow", "Config"))
        self.actionCreator.setText(_translate("PasolvMainWindow", "Creator"))
        self.actionPDC_Pasolv_Master.setText(_translate("PasolvMainWindow", "PDC Pasolv Master"))
